#!/usr/bin/env bash

set -e

echo "===> Bundling..."
script/bootstrap --quiet

var="PAGERDUTY_API_TOKEN"
if [[ -z "${!var}" ]]; then
    echo "Please export ${var}";
fi
echo "===> Running specs..."
(bundle exec rake)
